# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pintegraphql', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='photo',
            new_name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='image',
            name='liked_by',
        ),
        migrations.AlterField(
            model_name='image',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_images', to='pintegraphql.User'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
