# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pintegraphql', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='likes',
        ),
        migrations.AddField(
            model_name='image',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked', to='pintegraphql.User'),
        ),
    ]
