# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 03:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pintegraphql', '0002_auto_20161103_0332'),
        ('pintegraphql', '0002_auto_20161103_0330'),
    ]

    operations = [
    ]
