# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pintegraphql', '0002_auto_20161105_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_images', to='pintegraphql.User'),
        ),
    ]
