# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pintegraphql', '0003_merge_20161103_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='liked_by',
        ),
        migrations.AddField(
            model_name='image',
            name='likedBy',
            field=models.ManyToManyField(related_name='likedImages', to='pintegraphql.User'),
        ),
    ]
