# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pintegraphql', '0007_auto_20161104_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='likedBy',
        ),
        migrations.AddField(
            model_name='image',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_images', to='pintegraphql.User'),
        ),
    ]
